persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true

listener 1883
protocol mqtt
allow_anonymous true
max_connections -1

listener 9001
protocol websockets
allow_anonymous true

max_inflight_messages 0
max_queued_messages 100000
queue_qos0_messages true
message_size_limit 268435456

connection_messages true
sys_interval 10
autosave_interval 60
autosave_on_changes true

retry_interval 20
max_packet_size 268435456
keepalive_interval 60
